In [4]:
#pip install pandas

In [13]:
import pandas as pd

In [8]:
a=[10,20,30,40]
pd.Series(a)

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
a=[2.5,4.5,3.5]
pd.Series(a)

0    2.5
1    4.5
2    3.5
dtype: float64

In [31]:
c=["python","java","dsa"]
pd.Series(c)

0    python
1      java
2       dsa
dtype: str

In [21]:
e=[True,False]
pd.Series(a)

0    2.5
1    4.5
2    3.5
dtype: float64

In [30]:
f=[5+3j,8+7j]
pd.Series(f)

0    5.0+3.0j
1    8.0+7.0j
dtype: complex128

In [23]:
d={"names":["pooja","priya","preethi"],"marks":[60,70,80]}
pd.DataFrame(d)

     names  marks
0    pooja     60
1    priya     70
2  preethi     80

In [24]:
d={"names":["pooja","priya","preethi"],"marks":[60,70,80]}
pd.DataFrame(d)

     names  marks
0    pooja     60
1    priya     70
2  preethi     80

In [25]:
data=pd.read_csv("student.csv")
data

    NAME         ID'S  AGE  GENDER DEPARATEMENT
0  Shiva  32350684956   21    male          cse
1   Rani  32350684978   20  female          ece
2    sai  32350684942   21    male          eee
3   roja   3250684942   21  female          cse

In [36]:
data.colums

AttributeError: 'DataFrame' object has no attribute 'colums'

In [34]:
data.shape

(4, 5)

In [35]:
data.info

<bound method DataFrame.info of     NAME         ID'S  AGE  GENDER DEPARATEMENT
0  Shiva  32350684956   21    male          cse
1   Rani  32350684978   20  female          ece
2    sai  32350684942   21    male          eee
3   roja   3250684942   21  female          cse>

In [38]:
data1=pd.read_csv("ecommerce.csv")
data1

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [39]:
data1.colum

AttributeError: 'DataFrame' object has no attribute 'colum'

In [40]:
data1.shape

(5000, 12)

In [41]:
data.info

<bound method DataFrame.info of     NAME         ID'S  AGE  GENDER DEPARATEMENT
0  Shiva  32350684956   21    male          cse
1   Rani  32350684978   20  female          ece
2    sai  32350684942   21    male          eee
3   roja   3250684942   21  female          cse>